### ISSUE TITLE
.replaceAll() is not available in all browsers - site fails to load

### ISSUE THREAD

**Issue by x42** [paviliondev/discourse-layouts#12]
This breaks compatibility with users of Firefox < 77 and Chome < 85 (various tablet users).

https://github.com/paviliondev/discourse-layouts/blob/49a9309419a94fb9308d907ee9aa5ceec9c1246f/assets/javascripts/discourse/lib/layouts.js.es6#L101

results in
```
_ember_jquery-36a23101c869ab0dc53fc908de69adb785731593573d32bdeef416acc1076ef4.js:36991 Error while processing route: discovery.latest t.replaceAll is not a function
TypeError: t.replaceAll is not a function
at t.renderTemplate (...)
at t.n.setup (...)
```

**Comment by angusmcleod** [comment]
Thanks for the report. This should be address in this commit: https://github.com/paviliondev/discourse-layouts/commit/736fa7b99abf5e0c5473a2e815bc722e846adfb6

**Comment by x42** [comment]
Confirmed. Thank you for the quick fix!
